model = "gpt-5.2-codex"
model_provider = "openai"
model_reasoning_effort = "medium"
model_reasoning_summary = "auto"
model_verbosity = "medium"
model_supports_reasoning_summaries = false
notify = [ ]
approval_policy = "untrusted"
sandbox_mode = "workspace-write"
cli_auth_credentials_store = "file"
chatgpt_base_url = "https://chatgpt.com/backend-api/"
mcp_oauth_credentials_store = "auto"
project_doc_max_bytes = 32768
project_doc_fallback_filenames = []
file_opener = "vscode"
hide_agent_reasoning = false
show_raw_agent_reasoning = false
disable_paste_burst = false
windows_wsl_setup_acknowledged = false
check_for_update_on_startup = true

[[skills.config]]
experimental_use_unified_exec_tool = false
experimental_use_freeform_apply_patch = false

[sandbox_workspace_write]
exclude_slash_tmp = false
exclude_tmpdir_env_var = false
network_access = false
writable_roots = ["/home/barts/code"]

[shell_environment_policy]
inherit = "all"
ignore_default_excludes = true
exclude = []
set = {}
include_only = []
experimental_use_profile = false

[history]
persistence = "save-all"

[tui]
notifications = false
animations = true
show_tooltips = true

[feedback]
enabled = true

[notice]

[features]
shell_tool = true
web_search_request = true
unified_exec = false
shell_snapshot = false
apply_patch_freeform = false
exec_policy = true
experimental_windows_sandbox = false
elevated_windows_sandbox = false
remote_compaction = true
remote_models = false
powershell_utf8 = true
child_agents_md = false

[mcp_servers]

[model_providers]

[profiles]

[projects]

[otel]
log_user_prompt = false
environment = "dev"
exporter = "none"
trace_exporter = "none"
